### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ismailmazumder** [rewanthtammana/Damn-Vulnerable-Bank#20]
node:19) UnhandledPromiseRejectionWarning: SequelizeHostNotFoundError: getaddrinfo ENOTFOUND mysql mysql:3306
    at ConnectionManager.connect (/home/node/dvba/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:120:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rewanthtammana** [comment]
@ismailmazumder Can you add more context & steps to reproduce?

**Comment by rewanthtammana** [comment]
All the messages above are warnings. You just need wait for a while to allow mysql container to get up & running to establish a successful connection.

**Comment by Dylansmil** [comment]
> @ismailmazumder Can you add more context & steps to reproduce?

Do you have software for btc hacking
